spring.application.name=userapi [DEV]
logging.level.com.learn.userapi=DEBUG

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/userapi_db
spring.datasource.username=userapi_user
spring.datasource.password=userapi_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Logging for SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE